name=BMS26M833
version=1.0.1
author=BESTMODULES
maintainer=BESTMODULES<service@bestmodulescorp.com>
sentence=Arduino library for I2C access to the BMS26M833 Infrared Thermopile Array Mdoule
paragraph=Arduino library for I2C access to the BMS26M833 Infrared Thermopile Array Mdoule.We can use the library  to read 8*8 temperature pixel matrix(unit: ℃) and get some information about the module
category=Sensors
url=https://www.bestmodulescorp.com/
architectures=*

